const wishs = {
  en: [
    "You could finish reading a book.",
    "A new season of your favorite TV show could start and end.",
    "You could make progress on a personal project.",
    "You could go on a vacation or weekend getaway.",
    "You could finish a work project.",
    "You could start and stick to a new workout routine.",
    "You could learn a new skill or hobby.",
    "You could cook a few new meals or try out new restaurants.",
    "You could attend a concert or live event.",
    "You could meet new people and make new friends.",
    "You could fall in love or start a new relationship.",
    "You could get a promotion or job offer.",
    "You could receive an unexpected windfall of money.",
    "You could experience a natural disaster or extreme weather event.",
    "You could celebrate a holiday or special occasion.",
    "You could complete a home renovation or cleaning project.",
    "You could see a movie or binge-watch a new TV show.",
    "You could volunteer for a cause you care about.",
    "You could experience a moment of personal growth or self-discovery.",
    "You could take up meditation or mindfulness practices.",
    "You could buy a new piece of technology or gadget.",
    "You could witness something amazing or awe-inspiring.",
    "You could take a class or attend a workshop.",
    "You could make progress on your professional development goals.",
    "You could have a new and exciting opportunity come your way.",
    "You could start a new creative project, like writing a book or painting a picture.",
    "You could adopt a new pet.",
    "You could experience a major breakthrough or success.",
    "You could achieve a long-held dream or goal.",
    "You could encounter an obstacle or challenge that tests your resilience.",
    "You could break a bad habit or addiction.",
    "You could win a prize or competition.",
    "You could experience a moment of personal transformation.",
    "You could reconnect with an old friend or family member.",
    "You could experience a moment of pure joy or happiness.",
  ],

  zh: [
    "祝你一切顺利，幸福快乐！",
    "愿你的每一天都充满爱、欢笑和快乐！",
    "祝你梦想成真，万事如意！",
    "给你传递正能量，愿你心情愉悦！",
    "愿今天成为美好的开始！",
    "祝你心静如水，生活美满！",
    "愿你的人生充满冒险和刺激！",
    "祝你健康、幸福和繁荣！",
    "愿你的内心充满爱和善良！",
    "给你送去温暖的问候和美好的祝愿！",
    "愿你的努力得到回报，成果累累！",
    "祝你的人生充满阳光和快乐！",
    "愿你在所做的一切中都找到快乐和满足！",
    "愿你的梦想都成真，心愿都实现！",
    "祝你勇气十足，面对挑战无惧！",
    "愿你生活中时时刻刻都能够找到成功和幸福！",
    "给你送去正能量和美好的祝愿！",
    "祝你在人生的旅途中一路顺风！",
    "愿你的人生充满爱和美好！",
    "祝你一生都幸福、快乐、充满爱！",
    "愿你的一天充满欢笑和快乐！",
    "愿你的人生充满光明和美好！",
    "祝你的每一天都特别美好！",
    "愿你的一天充满爱和欢笑！",
    "愿你的所有愿望都成真，所有梦想都实现！",
    "给你送去爱、光明和正能量！",
    "祝你所有的努力都能获得成功和幸福！",
    "愿你的人生充满成功和幸福！",
    "愿你的一天充满友爱和同情心！",
    "祝你今天和以后都平安、快乐、幸福！",
    "愿你时时刻刻都被爱和正能量所包围！",
    "愿你的一天充满微笑和阳光！",
    "祝你的人生充满美好的意外和惊喜！",
    "愿你的每一个愿望都成真，每一个梦想都实现！",
    "给你送去真诚的祝福和美好的愿望！",
    "祝你所有的努力都得到回报和认可！",
    "愿你的一天充满和谐、平静和美好！",
    "祝你生命之树茁壮成长，人生道路一帆风顺！",
    "愿你在漫长的人生旅途中永远充满勇气和信心！",
    "给你送去真心祝福，祝你心想事成！",
    "祝你一天比一天更加美好和精彩！",
    "愿你的人生充满欢笑、快乐和幸福！",
    "祝你的每一天都充满爱和善意！",
    "愿你的生活中到处都是美丽的花朵和幸福的果实！",
    "祝你的人生充满激情和创造力！",
    "愿你的每一个努力都能够得到肯定和认可！",
    "给你送去美好的祝愿和正能量！",
    "祝你在未来的日子里充满信心和勇气！",
    "愿你的生活充满欢声笑语和温馨！",
    "祝你的人生充满自信、勇气和成就感！",
  ],
};
export default wishs;
